# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt

      - name: Install Wasm Rust target
        run: rustup target add wasm32-wasi

      - name: Install spin-test
        run: |
          mkdir spin-install
          cd spin-install
          curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash
          sudo mv spin /usr/local/bin/
          spin plugin install -u https://github.com/fermyon/spin-test/releases/download/canary/spin-test.json --yes

      - name: Install cargo-component
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-component

      - name: Make
        run: |
          make
          make spin-test
        env:
          RUST_LOG: spin=trace
