# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          components: clippy, rustfmt

      - name: "Install Wasm Rust target"
        run: rustup target add wasm32-wasi

      - name: Make
        run: make
        env:
          RUST_LOG: spin=trace